# Generated by Django 4.0.3 on 2022-03-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya se encuentra Registrada'}, max_length=100, unique=True, verbose_name='Ingrese nombre de la Sede')),
                ('direccion', models.CharField(max_length=100, verbose_name='Ingrese direccion')),
                ('telefono', models.CharField(max_length=10, verbose_name='Ingrese Telefono de contacto')),
                ('correo', models.EmailField(max_length=100, verbose_name='Digite correo electronico de contacto')),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField(verbose_name='Ingrese grado')),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.sede')),
            ],
        ),
    ]
