# Generated by Django 4.0.3 on 2022-03-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colegio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Ingrese grado'),
        ),
    ]
